version: '3'
services:
  slave:
    image: docker pull registry.jala.info/devops/jenkinsci/slave:3.27-1-alpine
    labels:
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: slave.jenkins=true
    links:
      - master:master
    volumes:
      - ./jenkins_slave:/var/jenkins_home
  master:
    image:
      "registry.jala.info/devops/jenkins/jenkins:2.107.3-alpine"
    ports:
      - "8080:8080"
      - "5000:5000"
    volumes:
      - ./jenkins:/var/jenkins_home

				